all: Main.class Heap.class MinHeap.class MaxHeap.class

Main.class: Main.java
	javac Main.java

HeapClass: Heap.java
	javac Heap.java

MinHeap.class: MinHeap.java
	javac MinHeap.java

MaxHeap: MaxHeap.java
	javac MaxHeap.java
