all: Main.class ListNode.class MoveToFrontOrganisingList.class OrganisingList.class TransposeOrganisingList.class

Main.class: Main.java
	javac Main.java

ListNodeClass: ListNode.java
	javac ListNode.java

MoveToFrontOrganisingList.class: MoveToFrontOrganisingList.java
	javac MoveToFrontOrganisingList.java

OrganisingList: OrganisingList.java
	javac OrganisingList.java

TransposeOrganisingList.class: TransposeOrganisingList.java
	javac TransposeOrganisingList.java